apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: gitops-reverser
    app.kubernetes.io/managed-by: kustomize
  name: service
  namespace: system
spec:
  clusterIP: 10.96.200.200  # This is required because kube-apiserver starts before CoreDNS
  ports:
    - name: webhook-server
      port: 443
      protocol: TCP
      targetPort: 9443
    - name: audit-server
      port: 9444
      protocol: TCP
      targetPort: 9444
    - name: metrics
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: gitops-reverser
