apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- name: gitops-reverser.configbutler.ai
  clientConfig:
    service:
      name: service
