apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitops-reverser
  name: gitops-reverser-selfsigned-issuer
  namespace: sut
spec:
  selfSigned: {}


