apiVersion: configbutler.ai/v1alpha1
kind: GitProvider
metadata:
  labels:
    app.kubernetes.io/name: gitops-reverser
    app.kubernetes.io/managed-by: kustomize
  name: sample
spec:
  repoUrl: "http://gitea-http.gitea-e2e.svc.cluster.local:13000/testorg/testrepo.git"
  allowedBranches:
    - "main"
  secretRef:
    name: "git-creds"
  push:
    interval: "1m"
    maxCommits: 20
