apiVersion: configbutler.ai/v1alpha1
kind: GitTarget
metadata:
  labels:
    app.kubernetes.io/name: gitops-reverser
    app.kubernetes.io/managed-by: kustomize
  name: sample
  namespace: default
spec:
  gitProviderRef:
    name: gitrepoconfig-sample
  branch: main
  baseFolder: clusters/default
