## Append samples of your project ##
resources:
  - configbutler.ai_v1alpha1_gitrepoconfig.yaml
  - configbutler.ai_v1alpha1_gitrepoconfig_with_accesspolicy.yaml
  - configbutler.ai_v1alpha1_watchrule.yaml
  - configbutler.ai_v1alpha1_clusterwatchrule.yaml
  - configbutler.ai_v1alpha1_gitdestination.yaml
  - v1alpha1_gitprovider.yaml
  - v1alpha1_gittarget.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
