apiVersion: configbutler.ai/v1alpha1
kind: GitProvider
metadata:
  labels:
    app.kubernetes.io/name: gitops-reverser
    app.kubernetes.io/managed-by: kustomize
  name: gitprovider-sample
spec:
  # TODO(user): Add fields here
