apiVersion: v2
name: gitops-reverser
description: >-
  A Kubernetes controller for two-way GitOps synchronization - reverse sync from
  Kubernetes to Git
type: application
version: 0.9.0
appVersion: 0.9.0
keywords:
  - gitops
  - kubernetes
  - controller
  - synchronization
  - git
  - reverse-sync
home: https://github.com/configbutler/gitops-reverser
sources:
  - https://github.com/configbutler/gitops-reverser
maintainers:
  - name: ConfigButler Team
    url: https://github.com/configbutler
annotations:
  org.opencontainers.image.description: GitOps Reverser - Two-way GitOps synchronization for Kubernetes
  org.opencontainers.image.source: https://github.com/configbutler/gitops-reverser
  org.opencontainers.image.vendor: ConfigButler
  artifacthub.io/changes: |
    - kind: changed
      description: Updated to HA-ready configuration with 2 replicas by default
    - kind: changed
      description: Aligned with config folder structure
    - kind: added
      description: Pod disruption budget enabled by default
    - kind: added
      description: Pod anti-affinity for HA deployment
  artifacthub.io/containsSecurityUpdates: 'false'
  artifacthub.io/prerelease: 'false'
  artifacthub.io/license: Apache-2.0
