apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitops-reverser
    control-plane: gitops-reverser
    pod-security.kubernetes.io/enforce: restricted
  name: sut
