apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitops-reverser
  name: gitops-reverser-service
  namespace: sut
spec:
  clusterIP: 10.96.200.200    # This is required because kube-apiserver starts before CoreDNS (so we use a fixed address)
  ports:
  - name: webhook-server
    port: 443
    protocol: TCP
    targetPort: 9443
  - name: audit-server
    port: 9444
    protocol: TCP
    targetPort: 9444
  - name: metrics
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/name: gitops-reverser
    control-plane: controller-manager

