apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: gitops-reverser
    app.kubernetes.io/managed-by: kustomize
  name: audit-serving-cert
  namespace: system
spec:
  # SERVICE_NAME and SERVICE_NAMESPACE are replaced in config/default/kustomization.yaml
  dnsNames:
  - AUDIT_SERVICE_NAME.SERVICE_NAMESPACE.svc
  - AUDIT_SERVICE_NAME.SERVICE_NAMESPACE.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: audit-webhook-server-cert
  privateKey:
    rotationPolicy: Always
